### PR TITLE
Add cancellation token to async methods

### PR DESCRIPTION
**Pull request by askazakov**

### CODE REVIEW

**Comment by nalgeon** [comment]
Why would anyone use this?

**Comment by askazakov** [comment]
> Why would anyone use this?

Because CancellationToken is way to organise cooperative cancellation in dotnet. Interesting case for me is cancel request to dadata api if user cancel request to my api:
```csharp
[HttpGet]
[Route("suggest")]
public async Task<SuggestResponse> Get([FromQuery] SuggestRequest request, CancellationToken ct)
{
   var  api = new SuggestClientAsync(configs.DadataApiKey);
   var dadataRequest = new SuggestAddressRequest(inputString);
   var dadataResponse = await _api.SuggestAddress(dadataRequest, ct); // <-- 
   return new SuggestResponse() { suggests = dadataResponse.suggestions.Select(s => s.value).ToArray() };
}
```
If user requests suggests and then closes page until getting response I would like to avoid call to external api if possible

**Comment by nalgeon** [comment]
Seems like an overkill to me. `CancellationToken` makes sense for long-running requests, which is not the case for Dadata API.

**Comment by askazakov** [comment]
> Seems like an overkill to me. `CancellationToken` makes sense for long-running requests, which is not the case for Dadata API.

It's not only for long-running requests.
Example: my server can serve 10 requests and can put extra 5 requests in queue (if queue is full server rejects request). If client decides not to wait in queue it's better to cancel request than proceed and throw result away.

**Comment by nalgeon** [comment]
Fair enough. Thank you for your contribution! Released as [21.9.0](https://github.com/hflabs/dadata-csharp/releases/tag/21.9.0), will be on NuGet soon.

**Pull request merged**
